pipeline:
  build:
    image: docker
    commands:
      - docker info
      - docker build --rm -t octocat/hello-world .
      #- docker run --rm octocat/hello-world --test
      #- docker login -u <username> -p <password>
      #- docker push octocat/hello-world
      #- docker rmi octocat/hello-world
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

#  publish:
#    image: plugins/docker
#    repo: foo/bar
#    tags: [ 1.0.0, 1.0, latest ]
